version: '3.8'

services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - app_network

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - app_network

  app1:
    build:
      context: .
      dockerfile: RateLimiters.Endpoints/Dockerfile
    ports:
      - "8086:8086"
    depends_on:
      - redis
      - mongodb
    networks:
      - app_network

  app2:
    build:
      context: .
      dockerfile: RateLimiters.Endpoints/Dockerfile
    ports:
      - "8085:8086"
    depends_on:
      - redis
      - mongodb
    networks:
      - app_network

  app3:
    build:
      context: .
      dockerfile: RateLimiters.Endpoints/Dockerfile
    ports:
      - "8084:8086"
    depends_on:
      - redis
      - mongodb
    networks:
      - app_network

volumes:
  mongodb_data:

networks:
  app_network:
    driver: bridge
